FROM node:20-alpine as builder
WORKDIR /build
COPY package*.json ./
RUN npm ci
COPY . .

FROM node:20-slim
WORKDIR /backend
ENV secret=1234
COPY  --from=builder  /build .
USER nonroot
EXPOSE 4000
CMD ["insert.js"]
