FROM node:20-alpine as builder
WORKDIR /build
COPY package*.json ./
RUN npm ci
COPY . .

FROM gcr.io/distroless/nodejs24-debian13
WORKDIR /backend
ENV secret=1234
COPY  --from=builder  /build .
CMD ["insert.js"]
